services:
  - type: web
    name: susep-api
    runtime: node
    region: oregon
    plan: free
    buildCommand: |
      npm install
      npm install puppeteer
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "false"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium-browser
    dockerfilePath: ./Dockerfile
